# server:
#   port: 8082

# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb
#     username: sa
#     password: 
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate.dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://my-db-ksk.ct0oke8kwc6m.ap-south-1.rds.amazonaws.com:5432/bugdb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

